<?xml version="1.0" encoding="UTF-8"?>
<!--DefiniciÃ³n del documento XML-->
<!DOCTYPE concesionario
[
    <!ELEMENT concesionario (coche*)>
    <!ELEMENT coche (marca, matricula, codigo, modelo)>
    <!ELEMENT codigo (#PCDATA)>
    <!ELEMENT matricula (#PCDATA)> 
    <!ELEMENT marca (#PCDATA)> 
    <!ELEMENT modelo (potencia, plazas, numPuertas)>
    <!ELEMENT potencia (#PCDATA)>
    <!ELEMENT plazas (#PCDATA)>
    <!ELEMENT numPuertas (#PCDATA)>

]>
<concesionario xmlns:g1="https://www.renault.es/">
    <g1:coche> 
        <codigo>64888974569b</codigo>
        <matricula>111bck</matricula>
        <marca>Renault</marca>
        <modelo>
            <potencia>400</potencia>
            <plazas>4</plazas>
            <numPuertas>3</numPuertas>
        </modelo>
        
    </g1:coche>
    <g1:coche> 
        <codigo>2584726842n</codigo>
        <matricula>6665bck</matricula>
        <marca>Renault</marca>
        <modelo>
            <potencia>425</potencia>
            <plazas>5</plazas>
            <numPuertas>4</numPuertas>
        </modelo>
        
    </g1:coche> 
    <g1:coche> 
        <codigo>333842652471x</codigo>
        <matricula>987FGH</matricula>
        <marca>Renault</marca>
        <modelo>
            <potencia>350</potencia>
            <plazas>4</plazas>
            <numPuertas>3</numPuertas>
        </modelo>       
    </g1:coche>
</concesionario>